### ISSUE TITLE
Update to 1.19.4

### ISSUE THREAD

**Issue by Felix14-v2** [edge217/BatteryStatusInfo#13]
After some changes in toasts BatteryStatusInfo doesn't work anymore in this version, so updating to 1.19.4 would be awesome

**Comment by Edgeburn** [comment]
You can download a 1.19.4 updated version of the mod [here](https://github.com/edge217/BatteryStatusInfo/suites/11991806178/artifacts/629510671), just extract the zip and add the non-sources jar to your mods folder. I haven't yet pushed this patch to CurseForge/Modrinth as I am working on improving compatibility with different computers (as I've had issues with it on Windows)

**Comment by Edgeburn** [comment]
A 1.19.4 compatible version of the mod is available on [Modrinth](https://modrinth.com/mod/batterystatusinfo) and [CurseForge](https://www.curseforge.com/minecraft/mc-mods/battery-status-info)
