### ISSUE TITLE
Busy-wait loop to get battery percentage

### ISSUE THREAD

**Issue by ScoreUnder** [edge217/BatteryStatusInfo#38]
This loop is going to significantly increase the battery usage and decrease the performance of the game:

https://github.com/edge217/BatteryStatusInfo/blob/6cc9ae96bfa02f33ea6804bb7c844c33b3a74284/src/main/java/com/edgeburnmedia/batterystatusinfo/BatteryCheckerThread.java#L48-L56

Without the battery status mod, Minecraft at the title screen uses a low amount of CPU. With the battery status mod, it uses that plus 100% of one core, and I suspect that this loop is the culprit. I would suggest using `Thread.sleep` to wait out the interval, and then interrupt the thread when that value changes. Might have a PR inbound if I don't have anything that needs doing today.

**Comment by Edgeburn** [comment]
Fixed in #39
